providers: []
# identityCenter: []
policySets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    identityCenterDependency: false
    policies:
      - name: vpc-flow-logs-policy
        policy: iam-policies/role-policy/vpc/vpc-flow-logs-policy.json
roleSets:
  - deploymentTargets:
      organizationalUnits:
        - Root
    roles:
      - name: EC2-Instance-Profile-SSM-Role
        instanceProfile: true
        assumedBy:
          - type: service
            principal: ec2.amazonaws.com
        policies:
          awsManaged:
            - AmazonSSMManagedInstanceCore
            - CloudWatchAgentServerPolicy
      - name: VPC-Flowlog-Role
        assumedBy:
          - type: service
            principal: vpc-flow-logs.amazonaws.com
        policies:
          customerManaged:
            - vpc-flow-logs-policy
      - name: Backup-Role
        assumedBy:
          - type: service
            principal: backup.amazonaws.com
        policies:
          awsManaged:
            - service-role/AWSBackupServiceRolePolicyForBackup
            - service-role/AWSBackupServiceRolePolicyForRestores
groupSets: []
userSets: []
